import {
  Activity,
  AlertCircle,
  ArrowRight,
  ArrowUpRight,
  Battery,
  BatteryFull,
  BatteryMedium,
  Bell,
  Bot,
  Brain,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Command,
  Compass,
  Cpu,
  Database,
  Download,
  Eye,
  Filter,
  Fingerprint,
  Globe,
  Headphones,
  History,
  Home,
  Image as ImageIcon,
  Languages,
  Layers,
  LineChart,
  Link as LinkIcon,
  Loader2,
  Lock,
  type LucideIcon,
  type LucideProps,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Mic,
  Moon,
  Network,
  Play,
  Plus,
  Radar,
  Radio,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Waves,
  Wifi,
  Zap,
  X,
  Glasses,
  ScanLine,
  Workflow,
  GitBranch,
  Mountain,
  Camera,
  RefreshCw,
  Repeat,
  Maximize2,
  Minimize2,
  ArrowDown,
  Pause,
  Power,
  HeartPulse,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertCircle,
  agent: Bot,
  arrow: ArrowRight,
  arrowDown: ArrowDown,
  arrowUpRight: ArrowUpRight,
  battery: Battery,
  batteryFull: BatteryFull,
  batteryMedium: BatteryMedium,
  bell: Bell,
  brain: Brain,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  command: Command,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  device: Glasses,
  download: Download,
  eye: Eye,
  filter: Filter,
  fingerprint: Fingerprint,
  globe: Globe,
  headphones: Headphones,
  history: History,
  home: Home,
  heart: HeartPulse,
  image: ImageIcon,
  languages: Languages,
  layers: Layers,
  chart: LineChart,
  link: LinkIcon,
  loader: Loader2,
  lock: Lock,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  message: MessageSquare,
  mic: Mic,
  moon: Moon,
  network: Network,
  pause: Pause,
  play: Play,
  plus: Plus,
  power: Power,
  radar: Radar,
  radio: Radio,
  refresh: RefreshCw,
  repeat: Repeat,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  timer: Timer,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  volume: Volume2,
  wave: Waves,
  wifi: Wifi,
  zap: Zap,
  x: X,
  glasses: Glasses,
  scan: ScanLine,
  workflow: Workflow,
  branch: GitBranch,
  mountain: Mountain,
  camera: Camera,
  maximize: Maximize2,
  minimize: Minimize2,
};

export function Icon({
  name,
  ...props
}: LucideProps & { name: keyof typeof map | string }) {
  const Cmp = map[name as string] ?? Sparkles;
  return <Cmp {...props} />;
}
